#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : pypi-yamllint
Version  : 1.28.0
Release  : 1
URL      : https://files.pythonhosted.org/packages/c8/82/4cd3ec8f98d821e7cc7ef504add450623d5c86b656faf65e9b0cc46f4be6/yamllint-1.28.0.tar.gz
Source0  : https://files.pythonhosted.org/packages/c8/82/4cd3ec8f98d821e7cc7ef504add450623d5c86b656faf65e9b0cc46f4be6/yamllint-1.28.0.tar.gz
Summary  : A linter for YAML files.
Group    : Development/Tools
License  : GPL-3.0
Requires: pypi-yamllint-bin = %{version}-%{release}
Requires: pypi-yamllint-license = %{version}-%{release}
Requires: pypi-yamllint-python = %{version}-%{release}
Requires: pypi-yamllint-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3
BuildRequires : pypi(pathspec)
BuildRequires : pypi(pyyaml)
BuildRequires : pypi(setuptools)

%description
yamllint
========
A linter for YAML files.
yamllint does not only check for syntax validity, but for weirdnesses like key
repetition and cosmetic problems such as lines length, trailing spaces,
indentation, etc.

%package bin
Summary: bin components for the pypi-yamllint package.
Group: Binaries
Requires: pypi-yamllint-license = %{version}-%{release}

%description bin
bin components for the pypi-yamllint package.


%package license
Summary: license components for the pypi-yamllint package.
Group: Default

%description license
license components for the pypi-yamllint package.


%package python
Summary: python components for the pypi-yamllint package.
Group: Default
Requires: pypi-yamllint-python3 = %{version}-%{release}

%description python
python components for the pypi-yamllint package.


%package python3
Summary: python3 components for the pypi-yamllint package.
Group: Default
Requires: python3-core
Provides: pypi(yamllint)
Requires: pypi(pathspec)
Requires: pypi(pyyaml)
Requires: pypi(setuptools)

%description python3
python3 components for the pypi-yamllint package.


%prep
%setup -q -n yamllint-1.28.0
cd %{_builddir}/yamllint-1.28.0
pushd ..
cp -a yamllint-1.28.0 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1669623642
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

pushd ../buildavx2/
export CFLAGS="$CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export CXXFLAGS="$CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FFLAGS="$FFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FCFLAGS="$FCFLAGS -m64 -march=x86-64-v3 "
export LDFLAGS="$LDFLAGS -m64 -march=x86-64-v3 "
python3 setup.py build

popd
%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pypi-yamllint
cp %{_builddir}/yamllint-%{version}/LICENSE %{buildroot}/usr/share/package-licenses/pypi-yamllint/31a3d460bb3c7d98845187c716a30db81c44b615 || :
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----
pushd ../buildavx2/
export CFLAGS="$CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export CXXFLAGS="$CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FFLAGS="$FFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FCFLAGS="$FCFLAGS -m64 -march=x86-64-v3 "
export LDFLAGS="$LDFLAGS -m64 -march=x86-64-v3 "
python3 -tt setup.py build install --root=%{buildroot}-v3
popd
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/yamllint

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pypi-yamllint/31a3d460bb3c7d98845187c716a30db81c44b615

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
